apiVersion: apps/v1
kind: Deployment
metadata:
  name: omicsdi-ddi-profile-deployment
spec:
  selector:
    matchLabels:
      app: omicsdi-ddi-profile-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: omicsdi-ddi-profile-pod
    spec:
      containers:
        - name: omicsdi-ddi-profile-pod
          imagePullPolicy: Always
          image: omicsdi/ddi-profile-service:omicsdi.dev.1
          env:
            - name: DDI_MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_DB
            - name: DDI_MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_USER
            - name: DDI_MONGO_PASSWD
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_PASSWD
            - name: DDI_MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_PORT
            - name: DDI_MONGO_MACHINE_ONE
              value: "mongod-0.mongodb-service.dev.svc.cluster.local"
            - name: DDI_MONGO_MACHINE_TWO
              value: "mongod-0.mongodb-service.dev.svc.cluster.local"
            - name: DDI_MONGO_MACHINE_THREE
              value: "mongod-0.mongodb-service.dev.svc.cluster.local"
            - name: DDI_MONGO_AUTH_DB
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_AUTH_DB
            - name: DDI_PROFILE_ENDPOINT
              value: "https://www.omicsdi.org/profilews"
            - name: DDI_ORCID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: ORCID_CLIENT_ID
            - name: DDI_ORCID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: ORCID_CLIENT_SECRET
            - name: DDI_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: TOKEN_SECRET
            - name: DDI_ORCID_FRONTEND_URL
              value: "https://orcid.org/"
            - name: DDI_ORCID_API_URL
              value: "https://api.orcid.org/v2.0/"
            - name: DDI_ORCID_PUB_URL
              value: "https://pub.orcid.org/v2.0/"
            - name: DDI_ORCID_AUTH_URL
              value: "https://orcid.org/oauth/authorize"
            - name: DDI_ORCID_TOKEN_URL
              value: "https://pub.orcid.org/oauth/token"
            - name: DDI_SECURITY_TARGET_URL
              value: "http://dev.omicsdi.org/profile"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: omicsdi-ddi-profile-service
  labels:
    app: omicsdi-ddi-profile-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: omicsdi-ddi-profile-pod
