apiVersion: apps/v1
kind: Deployment
metadata:
  name: omicsdi-ddi-profile-deployment
spec:
  selector:
    matchLabels:
      app: omicsdi-ddi-profile-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: omicsdi-ddi-profile-pod
    spec:
      containers:
        - name: omicsdi-ddi-profile-pod
          imagePullPolicy: Always
          image: omicsdi/ddi-profile-service:omicsdi.dev.01
          env:
            - name: DDI_MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_DB
            - name: DDI_MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_USER
            - name: DDI_MONGO_PASSWD
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_PASSWD
            - name: DDI_MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_PORT
            - name: DDI_MONGO_MACHINE_ONE
              value: "mongod-0.mongodb-service.dev.svc.cluster.local"
            - name: DDI_MONGO_MACHINE_TWO
              value: "mongod-0.mongodb-service.dev.svc.cluster.local"
            - name: DDI_MONGO_MACHINE_THREE
              value: "mongod-0.mongodb-service.dev.svc.cluster.local"
            - name: DDI_MONGO_AUTH_DB
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_AUTH_DB
            - name: DDI_PROFILE_ENDPOINT
              value: "https://www.omicsdi.org/profilews"
            - name: DDI_ORCID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: ORCID_CLIENT_ID
            - name: DDI_ORCID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: ORCID_CLIENT_SECRET
            - name: DDI_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: TOKEN_SECRET
            - name: DDI_ORCID_FRONTEND_URL
              value: "https://orcid.org/"
            - name: DDI_ORCID_API_URL
              value: "https://api.orcid.org/v2.0/"
            - name: DDI_ORCID_PUB_URL
              value: "https://pub.orcid.org/v2.0/"
            - name: DDI_ORCID_AUTH_URL
              value: "https://orcid.org/oauth/authorize"
            - name: DDI_ORCID_TOKEN_URL
              value: "https://pub.orcid.org/oauth/token"
            - name: DDI_SECURITY_TARGET_URL
              value: "http://dev.omicsdi.org/profile"
            - name: FACEBOOK_APP_KEY
              value: "1217968368302566"
            - name: FACEBOOK_APP_SECRET
              value: "541ee5c08daa6942264edbd416511f47"
            - name: FACEBOOK_APP_NAMESPACE
              value: "omicdi"
            - name: GITHUB_CLIENT_ID
              value: "fecb0da1d6c8a7ceed33"
            - name: GITHUB_CLIENT_SECRET
              value: "3ac75e6f4d348f2056bd0dd572e8e799bdd507ea"
            - name: TWITTER_CONSUMER_KEY
              value: "YMrGcvwC16hPlWDTMhzXul1xT"
            - name: TWITTER_CONSUMER_SECRET
              value: "uHAm1PCVETuFWxHcQc3hMw58JP2l4KC5XusVUyaGhAqwjuE83q"
            - name: ELIXIR_CLIENT_ID
              value: "4bb6b272-8fa4-4421-93a9-0e01e6815caa"
            - name: ELIXIR_CLIENT_SECRET
              value: "AI4soonZyeZ9JNbQQ4Nx8ZGMevLeCDyW6glVfktg109xnvCOk6MgE6k2LaMbERbIInKvbX8sK8k9mjMtgygdng4"
            - name: LINKEDIN_CLIENT_ID
              value: "86tjbycv3rxo1t"
            - name: LINKEDIN_CLIENT_SECRET
              value: "qTWcN3MMsZJEGPBu"
            - name: GOOGLE_CLIENT_ID
              value: "127176555632-1jevhjlj37ltk3t1m1pld16rq9dqn42n.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              value: "U5k2SMgUu61Rf2KvKTnvpELv"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: omicsdi-ddi-profile-service
  labels:
    app: omicsdi-ddi-profile-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: omicsdi-ddi-profile-pod
